data:
  data_raw: '/data/raw/sba_national.csv'
  data_train: '/data/raw/sba_train.csv'
  data_val: '/data/raw/sba_val.csv'
  data_test: '/data/raw/sba_test.csv'
  data_clean: '/data/clean/sba_clean.csv'
  clean_train: '/data/clean/clean_train.csv'
  train_subsam: '/data/clean/train_subsam.csv'
  train_smote: '/data/clean/train_smote.csv'

pipeline:
  preprocessing: '/models/preprocessing.joblib'
